language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
  script:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAIKFPN3SAZQHPIO7A
  secret_access_key:
    secure: GG8//z41o4bj/FTHW3HUgn60nYoleL3hPFxic/aR6uW0ffp/e9w6Fjy4oGSytoXPkFSbNBGlpjNiqUPHsfTWww8UfTOkujJnHvWe7qYe3rPfYfyTOV1xoPz7jJs24Sd2tX8IOM2wesdn9tFYEYTIgisWYoPcfHvTv6TM+o6VdYwB3Sla27TznAO4mx2NtG7nTKXYA92+YMbDjuP5QTPMpy2bqiPQQiObyWYZVVVDgj0o8N2ObFfcFYwQlgiZ3sXN6ybUr2EKdOeXykFykPnjafmV9VdvbLobdM8ch0Ke35Ryhr+yoHG3R5is8ZFC+xz3Igay4tNJnbhBW2e/vfNx55ySyIMYknDGhmmmOdnEM+1oUJC6hQ0vUG8oXRe9MyxICdocoRFJpTPqWIBOi+dedjPwgGCSJkdhEMhy0OM0/E/GzLQ0PYd0BT28sX0FDsGH0YLNI7aMjyfNdQf4DibwtZyjDYaqUFt1jTDTW+eE7ajjEzWnUBkdMiPlzWRTQGFx8vzg+WrcwLPF6F6UuWfzL423CBuUNVRs3bnzw27kCaN4zN0DrP3ierpaFeG5QA3NisE0AguVQrTbICusK22RRXLGnB2+3TRSw/SkkACZ35BOA4RzU4UfGNgkzl2MmZ4x8PaWNWYcoVstd2clDvYHaEXDiI5Qbw4aryGpdMebuyw=
  bucket: silverscreen.kevinellis.io
