language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
  script:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIAIKFPN3SAZQHPIO7A
  secret_access_key:
    secure: uRtRbw2RrEO/jVbQWbFQxJX1gK9SdYq+zcc6ouSevgtUXKc6PKetEgZpYrbyZwlaFkglQXvlAVSVL40laGzMm1pAWrvFef+1B/GBixQjAUe9HzXq8jDCWNNC1kEOK/0QJbXafQVzPINtqtWlDcxXl0I2uPD0v9CmUcEQW2ZuDLkJfEw62JnG04tHJTXkeMSwlHbQ2/OSozAidvDZ+uj5HLmEaRF5aIl1LjwYkrEk81YDX7TmTaBORvNKNxM30EVpEbvX+9khr2cmIxB9bVnbg/z8E8o915u8kgk1yXC/k40cK6FT74OrCbM0aSWcBYLzUbLWoavboUU7xNftCqAd6ppo/oIXxvwtMRlPLsX6Xk72Y9sk+/SKlt768Kk5wJrYKSf6anX/JEgIVxAC0Mnr/OrpLRwnngvyqeqtJLW2AbU1VLmmlVXcEcG8pv1KafL/0nr3obWKgNOnvmexPRpORyIGJuvZTcDNempVtZiwNvl64+N4vTFDDY1QpJnjpFujStDAPmuHRlVfRaitwnJk257B9JArAMtg0tBn/gvuK3zuqPCFv2naKWEr5tGwcThit6Nn0I633PBEKkUSOCdtbTJ2fY4HsPwOsOi7NEntt3qmuQ31P4S4qIKeKyghjn+MsHsCLcmG3iAdV/DL/FlXle/9TVYNVoeOUVsWd3MRUZA=
  bucket: silverscreen.kevinellis.io
  acl: public_read
  on:
    repo: kevellis124/silverscreen
