language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
  script:
  - npm run build
deploy:
  provider: s3
  access_key_id: AKIARDJL3XBAW5M2XAPK
  secret_access_key:
    secure: mHSuUpyHXQXff8P78rsnIQRPKoui1dgix6VOZRKF4AeEs1M3H4cLJlxibQDxLZwis6R8tmtU0WJz0Rtu7VPnWqzG7C+TFas17JIWwFcHz7paZBy1vAQiFZglVVMj92aGA0kgmS+8t0BjdpHY4qNdoU4As28Qjj9nPimTMqfRtG/1Xp553uIAFwlBVivf0E+B+rwvvx24V+8U7+h2q4MMkSHGjk9f3o9/1NG5DWQkwdJcej4jcmMzwe8/R3Fqt+EAk4BGNrsbBIa+oGCEX19hAcHAMWHPGYANFj0E+FARTAHhtjFU91Ik4HdlovxS3KIwSdBRqw/KnxF99pN+tBa7ol0JfR3IpBVqiJzBA3OkNVhSk5Y0wO7AauZpHZ3CBKBZhXKqZuLEtXq4TVfwEiOS05U1v86vEunJGVnv/BSIJSssd+9G8v3FyTW2VW0iUFDcD5Zg7AZ5u89lXuW3kRgZz4olUzjF88EX++ch10Rj12mhBLd/m8QcRIawynYFdRs0cewUhZWLsBd0dkGxuNZiKhgq43DePTt81i9QmSJVFkeN/y55RLgwsxCZF6tR8MtqhVswrjyCINebq0LYyrcv0hkWphlzeRgxlSP7gKHt86rtdKCA2+VIjWTORjn8loo9GXAFXzlnBE7IhsIbujly3RJN24sL6+BQMC3hTByPDyc=
  bucket: silverscreen.kevinellis.io
  acl: public_read
  on:
    repo: kevellis124/silverscreen
